### PR TITLE
Member card: Short bios cause centering + card section ordering improvements

### PR DESCRIPTION
**Pull request by NorseGaud**
Problem 1: On short bio member cards, the holo and bio are centered
Screen Shot 2021-05-15 at 4 48 21 PM

This looks weird since longer bio member cards look like this:
Screen Shot 2021-05-15 at 5 22 40 PM

They, in my opinion, should be consistent like the following:

Screen Shot 2021-05-15 at 5 26 52 PM

Problem 2: The bio area's sections seem out of order and could use a few improvements

Screen Shot 2021-05-15 at 5 24 32 PM
Screen Shot 2021-05-15 at 5 19 35 PM
Screen Shot 2021-05-15 at 5 19 30 PM

### CODE REVIEW

**Comment by brandonfancher** [comment]
@NorseGaud I agree with your conclusions, and I like the changes you're making.

A couple items (refer to screen shot below):

1. On the smallest of screens, can we use one column for social links? Otherwise, it breaks responsiveness.
2. The member statement paragraph is indented or padded on the left more than everything else. Can we left align it with the heading above it and the link below it?

image

Thanks!

**Review by brandonfancher — CHANGES_REQUESTED** [review]
See comment above. Otherwise, this is looking great!

**Comment by NorseGaud** [comment]
Ready for review @brandonfancher :)

**Comment by brandonfancher** [comment]
Still noticing a little bit of wonkiness:

image

I played with grid a bit...I think I have a tweak that will help this. Incoming.

**Comment by brandonfancher** [comment]
I rebased this in #206. (I guess it won't let me rebase your fork, @NorseGaud.) I'm going to close this one and merge #206. These are some good layout improvements. Thank you!

**Pull request closed without merging**
