### PR TITLE
issues/103: Add site footer

### PR DESCRIPTION
**Pull request by NorseGaud**
https://github.com/eoscommunity/Eden/issues/103

### CODE REVIEW

**Comment by brandonfancher** [comment]
Nathan! Thanks for the PRs, man! This is a great first issue and something we definitely need. A few things I'd like to see before we merge this:

* It should stick to the bottom of the window.
image
* It should appear on every page. I noticed I don't see it on `/community` or `/members`
* I also recommend using the Eden SVG logo here: 
image
* Let's remove the Copyright for now (and 2020). We'll find something else to put down there soon. Our copyright is the right to copy. haha.

You'll prob want to start with a rebase.

Thanks!

**Comment by NorseGaud** [comment]
@brandonfancher got it! Tailwind is new for me and I'm liking it :)

> I also recommend using the Eden SVG logo here:

So, this looks really bad on the first page since the logo shows twice in the same side, on the same page. I opted to just add "We are..." which flows into the statement.

**Review by brandonfancher — CHANGES_REQUESTED** [review]
Yeah, this is coming together! As can be seen in the screenshot below, for some reason, it's making the document larger than the viewport height by a few pixels. It scrolls when it shouldn't. Is that happening for you? Maybe you can track that down?

image

After that's resolved, I'll massage some of the links in the footer and we'll get this merged.

**Comment by NorseGaud** [comment]
@brandonfancher , good catch! It was a simple padding issue.

**Comment by brandonfancher** [comment]
Almost there! (And sorry to keep sending feedback piecemeal.)

We need to ensure everything's responsive.

image

**Review by brandonfancher — CHANGES_REQUESTED** [review]
See previous comment (responsive).

**Comment by NorseGaud** [comment]
> See previous comment (responsive).

Could you clarify for me what specifically is wrong? Maybe detail what in the screenshot is wrong?

**Comment by NorseGaud** [comment]
@brandonfancher I'm not seeing what you're seeing (I might not have access). If the footer doesn't fit with a page that I don't see, could we merge this and you add the small changes necessary to get it to play well? All of the pages I seem to have access to work fine.

Also, could you provide a little more specific information about the concerns? The screenshot helps, but I end up having to guess as to what you really want.

**Comment by brandonfancher** [comment]
> @brandonfancher I'm not seeing what you're seeing (I might not have access). If the footer doesn't fit with a page that I don't see, could we merge this and you add the small changes necessary to get it to play well? All of the pages I seem to have access to work fine. Otherwise, how do I reproduce what you're seeing?

Regarding the responsive problems, I'm referring to the home page, not private pages that you wouldn't have access to.

> Also, could you provide a little more specific information about the concerns? The screenshot helps, but I end up having to guess as to what you really want.

If we just drop the links _under_ the "We are..." paragraph at smaller breakpoints and with appropriate padding, we should be good.

I see you just pushed another tweak. I'll take a look when I have a chance.

**Comment by github-service-user-veertu** [comment]
> > @brandonfancher I'm not seeing what you're seeing (I might not have access). If the footer doesn't fit with a page that I don't see, could we merge this and you add the small changes necessary to get it to play well? All of the pages I seem to have access to work fine. Otherwise, how do I reproduce what you're seeing?
> 
> Regarding the responsive problems, I'm referring to the home page, not private pages that you wouldn't have access to.
> 
> > Also, could you provide a little more specific information about the concerns? The screenshot helps, but I end up having to guess as to what you really want.
> 
> If we just drop the links _under_ the "We are..." paragraph at smaller breakpoints and with appropriate padding, we should be good.
> 
> I see you just pushed another tweak. I'll take a look when I have a chance.

Ah, yes, I see, stacked links is fine and possible. I'll make a change tonight to do that. Thanks @brandonfancher

**Comment by NorseGaud** [comment]
> > @brandonfancher I'm not seeing what you're seeing (I might not have access). If the footer doesn't fit with a page that I don't see, could we merge this and you add the small changes necessary to get it to play well? All of the pages I seem to have access to work fine. Otherwise, how do I reproduce what you're seeing?
> 
> Regarding the responsive problems, I'm referring to the home page, not private pages that you wouldn't have access to.
> 
> > Also, could you provide a little more specific information about the concerns? The screenshot helps, but I end up having to guess as to what you really want.
> 
> If we just drop the links _under_ the "We are..." paragraph at smaller breakpoints and with appropriate padding, we should be good.
> 
> I see you just pushed another tweak. I'll take a look when I have a chance.

Ah yes, I see. Stacking is possible and I'll work on that tonight. Thanks @brandonfancher

**Comment by NorseGaud** [comment]
@brandonfancher I think I got it this time ;)

**Review by brandonfancher — APPROVED** [review]
Looks great. 💥  I'll get this merged. As for the links, I'll massage those post merge. 

This is awesome. Excellent contribution. Thank you, @NorseGaud!

**Pull request merged**
